### ISSUE TITLE
 Review请求

### ISSUE THREAD

**Issue by Cactusstudent** [WuzgXY-GitHub/WuzgXY-GitHub#3]
hi, 你好。
最开始是在匠魂官方的仓库中，发现了你参与了匠魂2汉化的部分工作。由于匠魂官方仓库的#4759翻译质量确实看不了，机翻痕迹严重（见下方相关链接 [TinkerConstruct PR #4759] ）。所以我们最近向匠魂官方提交了一份由我们7个人共同制作的1.18.2版本的汉化，想请您Review或者是提提意见也好。这会对我们完善汉化有极大的帮助，谢谢您！
相关链接
[TinkerConstruct PR #4759](https://github.com/SlimeKnights/TinkersConstruct/pull/4759)
[TinkerConstruct PR #4957](https://github.com/SlimeKnights/TinkersConstruct/pull/4957)
[TinkerConstruct 翻译文本存放地](https://github.com/HaloSense/TiC3-Translation)

**Comment by WuzgXY-GitHub** [comment]
承蒙好意。大致浏览下来改自派版或星版，那么致命的大问题应该已经消除了，剩下的小细节恕我无能力也无兴趣纠正。
